spring.application.name=order-service

server.port = 8080

# KAFKA PRODUCER CONFIG
spring.kafka.bootstrap-servers=localhost:9092

# Producer serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# This ensures JSON is sent in a readable form
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ACTUATOR / PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
