spring.application.name=inventory-service

server.port = 8081

# KAFKA CONSUMER CONFIG
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group
spring.kafka.consumer.group-id=inventory-group

# Consumer deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages (simple for dev)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Start reading from earliest if no offset
spring.kafka.consumer.auto-offset-reset=earliest

# ACTUATOR / PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
